### ISSUE TITLE
Upgrade Dashboard to React.js (or Next.js)

### ISSUE THREAD

**Issue by ZeeshanJan** [Blockchain-Technology-Lab/edi-frontend#1]
Currently, our dashboard is built using simple HTML/JS, which has served its purpose well. However, as our project grows in complexity and scale, it's becoming apparent that transitioning to a more robust frontend framework like React.js (or Next.js) would offer numerous advantages in terms of maintainability, scalability, and developer productivity.

**Objective**:

The objective of this issue is to plan and execute the migration of our dashboard to React.js (or Next.js). This transition will involve rewriting the existing HTML/JS codebase using React components (or Next.js pages) while ensuring that the functionality and design remain intact.

Any feedback or suggestions regarding the choice of framework or the migration process are welcome and encouraged.

**Comment by dhaval-codes** [comment]
I want to contribute to this, is there any thing more I should know or understand before making it from scratch?

**Comment by ZeeshanJan** [comment]
Hi @dhaval-codes - thank you for your intent to contribute to the issue. We would appreciate your time and efforts.
Yes, please, if you can convert it to ReactJS, would be helpful.

**Comment by dhaval-codes** [comment]
Okay so do you want me to create a branch from this repo itself, or should I create a new project all together, initialise a private repo for it and share the link with you
